import { test } from 'node:test';
import assert from 'node:assert/strict';
import { EvidenceEngine, normalizeRecords, requiredSamplePerGroup } from '../lib/services';
import { handleApi } from '../lib/api';
test('imports pseudonymize technicians and preserve unknown outcomes',()=>{const [row]=normalizeRecords([{job_id:'one',technician_id:'Jane',callback_within_30_days:'unknown'}]);assert.match(row.technicianId,/^tech_[a-f0-9]{12}$/);assert.equal(row.callback,null);assert(!JSON.stringify(row).includes('Jane'));assert.throws(()=>normalizeRecords([{job_id:'a'},{job_id:'a'}]),/Duplicate/);});
test('insufficient records cannot yield findings',async()=>{const engine=new EvidenceEngine();const ready=engine.readiness(normalizeRecords([{job_id:'a'}]));assert.equal(ready.eligible,false);assert(ready.missing.length>=4);await assert.rejects(engine.analyze([]),/not connected/);});
test('sample size is calculated rather than using the historical matched sample',()=>{assert(requiredSamplePerGroup()>1000);assert(requiredSamplePerGroup(.1,.05)<requiredSamplePerGroup());});
test('human approval and a validated trial are required for process changes',async()=>{const process=await handleApi('POST',['processes'],{title:'Test isolated baseline',equipment:'Valve X'}) as {id:string};await assert.rejects(handleApi('POST',['processes',process.id,'publish'],{steps:[{id:'a',action:'Check'}]}),/approval/);await assert.rejects(handleApi('POST',['change-requests'],{trialId:'missing'}),/validated/);});
test('complete demo loop preserves published baseline while submitting proposed v2',async()=>{const scan=await handleApi('POST',['scans'],{processId:'valve-replacement',demo:true}) as {id:string};await assert.rejects(handleApi('POST',['scans',scan.id,'run'],{}),/Not enough/);await handleApi('POST',['scans',scan.id,'readiness'],{});await handleApi('POST',['scans',scan.id,'run'],{});const trial=await handleApi('POST',['trials'],{findingId:'finding-18',equipment:'Valve X',testGroup:'Eligible test jobs'}) as {id:string};await assert.rejects(handleApi('POST',['change-requests'],{trialId:trial.id}),/validated/);await handleApi('POST',['trials',trial.id,'results'],{sample:true});const change=await handleApi('POST',['change-requests'],{trialId:trial.id}) as {id:string};await handleApi('POST',['change-requests',change.id,'submit'],{proposedStep:'Wait and repeat pressure test.'});const process=await handleApi('GET',['processes','valve-replacement']) as {currentVersion:number};assert.equal(process.currentVersion,1);});
